require("user.plugins")
require("user.options")

require("user.keymaps")
require("user.autocmds")
require("user.lsp")

require("user.treesitter")
require("user.telescope")
require("user.which-key")
require("user.neoscroll")
require("user.surround")
require("user.bookmark")
require("user.numb")
require("user.todo-comments")
require("user.harpoon")
require("user.inlay-hints")
require("user.colorizer")
require("user.spectre")
require("user.cybu")
require("user.smart-split")
require("user.bqf")
require("user.zen-mode")
require("user.jaq")
require("user.dial")
require("user.neogit")
require("user.comment")
